# Generated by Django 4.2.2 on 2023-06-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_ingredientes_ingrediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
